name: Build PlatformIO Game Host
run-name: Build PlatformIO Game Host

on:
  push:
    branches: [ "main" ]
    paths:
      - 'DartsBoard/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'DartsBoard/**'      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -d ${{ github.workspace }}/DartsBoard/
        
      - uses: actions/upload-artifact@v4
        with:
          name: Darts-Game-Host
          path: ${{ github.workspace }}/DartsBoard/.pio/build/due/firmware.bin
